<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="XenoAtom.Terminal.UI" Version="3.9.0"/>
        <PackageReference Include="Tomlyn" Version="2.10.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Straumr.Console.Shared\Straumr.Console.Shared.csproj"/>
        <InternalsVisibleTo Include="Straumr.Keybinds.Check"/>
    </ItemGroup>

</Project>
