<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <ApplicationIcon>icon.ico</ApplicationIcon>
        <Company>Albin Alm</Company>
        <Product>Straumr</Product>
        <AssemblyName>straumr</AssemblyName>
        <IncludeTui Condition="'$(IncludeTui)' == ''">true</IncludeTui>

        <!-- Suppress AOT/trim warnings from third-party packages -->
        <NoWarn>$(NoWarn);IL2026;IL2104;IL3000;IL3053</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IncludeTui)' == 'true'">
        <DefineConstants>$(DefineConstants);INCLUDE_TUI</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Straumr.Console.Cli\Straumr.Console.Cli.csproj" />
        <ProjectReference Include="..\Straumr.Console.Tui\Straumr.Console.Tui.csproj"
                          Condition="'$(IncludeTui)' == 'true'" />
        <ProjectReference Include="..\Straumr.Console.Shared\Straumr.Console.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <IntegrationRootDescriptor Include="..\Straumr.Console.Cli\CliRoots.xml" Condition="Exists('..\Straumr.Console.Cli\CliRoots.xml')" />
        <TrimmerRootDescriptor Include="@(IntegrationRootDescriptor)" />
        <TrimmerRootDescriptor Include="MyRoots.xml" />
    </ItemGroup>

</Project>
